#pragma once

#define LEARNING_RATE 0.75f

#define RANDOM_ACTION_RATE 0.8f

#define NUM_HIDDEN_LAYER 1;
#define NUM_STATE_VARIABLES 3
#define NUM_STATE_ACTIONS 2

#define SD_MAX_ANGULAR_VELOCITY 9.f;
#define EB_MAX_ANGULAR_VELOCITY 9.f;

#define STEP_DELAY 10
#define COLLISION_CNT_MAX 10