#pragma once

#define LEARNING_RATE 0.05f
#define RANDOM_ACTION_RATE 0.2f

#define NUM_STATE_VARIABLES 3
#define NUM_STATE_ACTIONS 2

#define SD_MAX_ANGULAR_VELOCITY 9.f;
#define EB_MAX_ANGULAR_VELOCITY 9.f;